version: '2'
services:

  web-ctn:
    image: richarvey/nginx-php-fpm:1.3.7
    restart: always
    environment:
     - SKIP_COMPOSER=1
     - RUN_SCRIPTS=0
    ports:
     - "80:80"
     - "443:443"
    extra_hosts:     
     - "chrome-ext-notification.local:127.0.0.1"
    volumes:     
     - ../sample-project/backend:/var/www/html/notification/
     - ./conf/:/etc/nginx/sites-enabled/
     - ./ssl/:/etc/nginx/ssl/
    depends_on:
     - mysql

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "6603:3306"
    volumes:            
        - ../sample-project/yii2-realtime.sql:/docker-entrypoint-initdb.d/yii2-realtime.sql
        - /var/lib/mysql  
    environment:
        - MYSQL_DATABASE=yii2-realtime        
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root

  # node-server:
  #   build: ./nodejs
  #   container_name: node-server
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql
  #   volumes:
  #     - "../sample-project/nodeServer:/app"